name: app_test CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install coverage
        pip install flake8==6.0.0
        pip install selenium==4.1.0
        pip install webdriver-manager==3.8.5
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f othertest_requirements.txt ]; then pip install -r othertest_requirements.txt; fi
    - name: run chagpt_telegram_bot
      run: |
        bash run.sh
    - name: application test
      run: |
        cd app_test
        python app_test.py
    - name: application group test
      run: |
        cd app_test
        python app_test_group.py