name: security_test CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd app_test
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: python fuzz test
      run: |
        cd fuzz_test
        python main_fuzz.ppy
        python openai_helper_fuzz.py
        python telegram_bot_fuzz.py
        python usage_tracker_fuzz.py
        python utils_fuzz.py
    - name: afl test
      run: 
        py-afl-fuzz -m 200 -t 5000+ -o results/ -i bot/ -- python fuzz_test/afl_test.py

        