name: fuzz_test CI
on:
  push:
    branches:
      - main

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f othertest_requirements.txt ]; then pip install -r othertest_requirements.txt; fi

      - name: Run main fuzz test
        run: |
          cd fuzz_test
          python main_fuzz.py
        timeout-minutes: 1

      - name: Run openai helper fuzz test
        run: |
          cd fuzz_test
          python openai_helper_fuzz.py
        timeout-minutes: 1

      - name: Run telegram bot fuzz test
        run: |
          cd fuzz_test
          python telegram_bot_fuzz.py
        timeout-minutes: 1

      - name: Run usage tracker fuzz test
        run: |
          cd fuzz_test
          python usage_tracker_fuzz.py
        timeout-minutes: 1

      - name: Run utils fuzz test
        run: |
          cd fuzz_test
          python utils_fuzz.py
        timeout-minutes: 1

      - name: Run afl test
        run: |
          cd fuzz_test
          py-afl-fuzz -m 200 -t 5000+ -o results/ -i bot/ -- python afl_test.py
        timeout-minutes: 3
