name: fuzz_test CI
on:
  push:
    branches:
      - main

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f othertest_requirements.txt ]; then pip install -r othertest_requirements.txt; fi
          
#      - name: Install afl-fuzz
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y afl

#      - name: Run afl test
#        run: |
#          export AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES=1
#         timeout -k 30s 3m py-afl-fuzz -m 200 -t 5000+ -o results/ -i bot/ -- python afl_test.py || true
          
      - name: Run atheris main fuzz test
        run: |
          cd fuzz_test
          timeout -k 30s 1m python main_fuzz.py  || true

      - name: Run atheris openai helper fuzz test
        run: |
          cd fuzz_test
          timeout -k 30s 1m python openai_helper_fuzz.py  || true

      - name: Run atheris telegram bot fuzz test
        run: |
          cd fuzz_test
          timeout -k 30s 1m python telegram_bot_fuzz.py  || true

      - name: Run atheris usage tracker fuzz test
        run: |
          cd fuzz_test
          timeout -k 30s 1m python usage_tracker_fuzz.py || true

      - name: Run atheris utils fuzz test
        run: |
          cd fuzz_test
          timeout -k 30s 1m python utils_fuzz.py || true


