name: security_test CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f othertest_requirements.txt ]; then pip install -r othertest_requirements.txt; fi

    - name: Lint with pylint
      run: |
        cd bot
        pylint main.py || true
        pylint openai_helper.py || true
        pylint telegram_bot.py || true
        pylint usage_tracker.py || true
        pylint utils.py || true
    - name: Lint with bandit
      run: |
        cd bot
        bandit main.py || true
        bandit openai_helper.py || true
        bandit telegram_bot.py || true
        bandit usage_tracker.py || true
        bandit utils.py || true
    - name: Lint with flake8 
      run: |
        cd bot
        flake8 main.py || true
        flake8 openai_helper.py || true
        flake8 telegram_bot.py || true
        flake8 usage_tracker.py || true
        flake8 utils.py || true
