name: security_test CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8
        cd app_test
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8 ,pylint, bandit
      run: |
        cd bot
        flake8 .
      run: |
        cd bot
        pylint main.py
        pylint openai_helper.py
        pylint telegram_bot.py
        pylint usage_tracker.py
        pylint utils.py
      run: |
        cd bot
        bandit main.py
        bandit openai_helper.py
        bandit telegram_bot.py
        bandit usage_tracker.py
        bandit utils.py