name: telegram_bot CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install coverage
        if [ -f unittest-requirements.txt ]; then pip install -r unittest-requirements.txt; fi

    - name: Test with unittest and coverage report
      run: |
        cd unittest
        python -m coverage run -m unittest test_help.py test_image.py test_other_methods.py test_prompt.py test_prompt.py test_resend.py test_reset.py test_stat.py test_transcribe.py 
        coverage report

